### ISSUE TITLE
Ran into error on fresh install and npm start attempt: Cannot find namespace 'webdriver'.

### ISSUE THREAD

**Issue by kevindashgit** [angular/quickstart#326] opened 2016-12-20 08:56 UTC
Found this guy: http://stackoverflow.com/questions/41232228/running-npm-start-fails-due-to-error

From a recent `npm info @types/selenium-webdriver` looks like `'2.53.37'` is out and there may be some issue with it or with out it worked with your thing etc...

At any rate - I tried solution mentioned by user `user1952133` - seemed to work just fine - which was to just use a static, older version - `2.53.33` in this case.

**Comment by filipesilva** [comment] 2016-12-20 11:29
Dupe of https://github.com/angular/quickstart/issues/325, the solution there is pretty much what you mention.

**Closed by filipesilva** 2016-12-20 11:29 UTC
