### ISSUE TITLE
Error after 'npm start'

### ISSUE THREAD

**Issue by ivanzvakoms** [angular/quickstart#52] opened 2016-04-04 15:56 UTC
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'tsc:w' ]
2 info using npm@3.8.5
3 info using node@v5.10.0
4 verbose run-script [ 'pretsc:w', 'tsc:w', 'posttsc:w' ]
5 info lifecycle angular2-quickstart@1.0.0~pretsc:w: angular2-quickstart@1.0.0
6 silly lifecycle angular2-quickstart@1.0.0~pretsc:w: no script for pretsc:w, continuing
7 info lifecycle angular2-quickstart@1.0.0~tsc:w: angular2-quickstart@1.0.0
8 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ivan-zakharchuk/Documents/Tutorials/quickstart/node_modules/.bin:/usr/local/bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ivan-zakharchuk/Documents/Tutorials/quickstart/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: CWD: /Users/ivan-zakharchuk/Documents/Tutorials/quickstart
11 silly lifecycle angular2-quickstart@1.0.0~tsc:w: Args: [ '-c', 'tsc -w' ]
12 silly lifecycle angular2-quickstart@1.0.0~tsc:w: Returned: code: 1  signal: null
13 info lifecycle angular2-quickstart@1.0.0~tsc:w: Failed to exec tsc:w script
14 verbose stack Error: angular2-quickstart@1.0.0 tsc:w: `tsc -w`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-quickstart@1.0.0
16 verbose cwd /Users/ivan-zakharchuk/Documents/Tutorials/quickstart
17 error Darwin 15.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc:w"
19 error node v5.10.0
20 error npm  v3.8.5
21 error code ELIFECYCLE
22 error angular2-quickstart@1.0.0 tsc:w: `tsc -w`
22 error Exit status 1
23 error Failed at the angular2-quickstart@1.0.0 tsc:w script 'tsc -w'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc -w
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

and if I just type ' tsc -w'
```
fs.js:1315
    throw error;
    ^

Error: watch /users/ivan-zakharchuk/documents/tutorials/quickstart ENOENT
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at addDirWatcher (/usr/local/lib/node_modules/typescript/lib/tsc.js:1036:39)
    at Object.addFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1051:21)
    at Object.watchFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1172:48)
    at Object.executeCommandLine (/usr/local/lib/node_modules/typescript/lib/tsc.js:34532:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsc.js:34863:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

operating system - OSX
node -v v5.10.0
 tsc -v Version 1.8.9

**Comment by ivanzvakoms** [comment] 2016-04-04 15:57
and if I just type ' tsc -w'
```
fs.js:1315
    throw error;
    ^

Error: watch /users/ivan-zakharchuk/documents/tutorials/quickstart ENOENT
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at addDirWatcher (/usr/local/lib/node_modules/typescript/lib/tsc.js:1036:39)
    at Object.addFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1051:21)
    at Object.watchFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1172:48)
    at Object.executeCommandLine (/usr/local/lib/node_modules/typescript/lib/tsc.js:34532:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsc.js:34863:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by Foxandxss** [comment] 2016-04-04 16:17
That is really weird. For the sake of trying. Clone the repo again in a new folder, it is like tsc is not finding the folder. I cannot reproduce :/

**Comment by ivanzvakoms** [comment] 2016-04-04 19:22
Yeah, I've tried this, but nothing happened) I'm going to try this on another OSX machine.

**Comment by ivanzvakoms** [comment] 2016-04-05 09:39
Downgrade to tsc 1.7.5 - fixes this problem.

**Comment by Foxandxss** [comment] 2016-04-05 10:16
I am using latest typescript (global and in the package) and works for me in OSX.

**Comment by ivanzvakoms** [comment] 2016-04-05 11:38
As I understand this issues is connected to https://github.com/Microsoft/TypeScript/issues/7154

**Comment by qheolet** [comment] 2016-04-12 20:37
Same Error Here... 
node_modules/angular2/platform/browser.d.ts(77,90): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(83,60): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(83,146): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(96,51): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(96,147): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(133,90): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(171,81): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/change_detection/differs/default_keyvalue_differ.d.ts(23,15): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/differs/default_keyvalue_differ.d.ts(25,16): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(4,42): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(14,13): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(24,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(25,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/provider.d.ts(436,103): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/linker/compiler.d.ts(12,50): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/compiler.d.ts(16,41): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(108,136): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(156,150): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(197,128): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(203,127): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(204,141): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(205,119): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/render/api.d.ts(13,13): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/render/api.d.ts(14,84): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(101,41): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(102,22): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(103,25): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/platform/browser/browser_adapter.d.ts(75,33): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/platform/dom/dom_adapter.d.ts(85,42): error TS2304: Cannot find name 'Map'.
node_modules/rxjs/CoreOperators.d.ts(35,67): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(50,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(89,67): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(94,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(94,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(46,62): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(47,42): error TS2304: Cannot find name 'Iterator'.
node_modules/rxjs/Observable.d.ts(103,74): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(103,84): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(143,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(158,65): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(201,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(206,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(206,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/ForkJoinObservable.d.ts(6,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/ForkJoinObservable.d.ts(7,58): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/FromObservable.d.ts(7,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/FromObservable.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.
node_modules/rxjs/observable/PromiseObservable.d.ts(9,31): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/PromiseObservable.d.ts(10,26): error TS2304: Cannot find name 'Promise'.

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "npm run lite" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "npm run lite" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run lite" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juancarlosduran/Desktop/ShakeShi/npm-debug.log


maybe is related...

**Comment by zerooverflow** [comment] 2016-04-13 08:53
windows7, with latest typescript 1.8.10, i can only npm run tsc:w and npm run lite in two shells.
npm start get the same npm run tsc error:

...
8 info angular2-quickstart@1.0.0 Failed to exec start script
9 verbose stack Error: angular2-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
9 verbose stack Exit status 2
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
...

**Comment by Foxandxss** [comment] 2016-04-13 10:13
Ill try on my windows box later.

**Comment by wardbell** [comment] 2016-04-18 02:24
closing because there is not defined, repeatable error here.

**Closed by wardbell** 2016-04-18 02:24 UTC

**Comment by vasicvuk** [comment] 2016-06-01 07:27
I have same error on Windows 10 (tried Node JS 4 and 5 with no luck). Npm run and tsc run one by one but start is not working

**Comment by guillaumesoul** [comment] 2016-06-12 21:03
same error for me on Mac OS X el capitan

**Comment by chfw** [comment] 2016-06-14 07:38
same error on windows 8, node 4.2.4 and npm 3.5.2 with angular release candidate 1.

**Comment by rafalskyi** [comment] 2016-06-24 01:41
@wardbell, same error on Mac OS X el capitan (IMPORTANT: system was installed as case sensitive)
node v5.6.0 
npm 3.6.0
tsc   1.8.10

**Comment by hbf** [comment] 2016-07-20 17:03
Same here:

```
$ node -v; npm -v; ./node_modules/.bin/tsc -v
v5.4.1
3.5.3
Version 1.8.10
```

MacOS 10.11.1 (El Capitan)
