### ISSUE TITLE
tsc -w exited with code 126

### ISSUE THREAD

**Issue by ivaro18** [angular/quickstart#234] opened 2016-09-30 08:10 UTC
npm -v : 3.10.8
node -v : v4.5.0

(converted debuq.log to txt cause github doesn't allow me to post .log)

[npm-debug.txt](https://github.com/angular/quickstart/files/502390/npm-debug.txt)

After following this quickstart (git clone, npm install and npm start), I get an error:

    $ npm start

    > angular-quickstart@1.0.0 start C:\Users\Ivar\documents\school\stage\workspace\v2\quickstart
    > tsc && concurrently "tsc -w" "lite-server"

    [0] /c: /c: is a directory
    [1] /c: /c: is a directory
    [0] tsc -w exited with code 126
    [1] lite-server exited with code 126

    npm ERR! Windows_NT 10.0.14393
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ivar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
    npm ERR! node v4.5.0
    npm ERR! npm  v3.10.8
    npm ERR! code ELIFECYCLE
    npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     tsc && concurrently "tsc -w" "lite-server"
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs angular-quickstart
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls angular-quickstart
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\Ivar\documents\school\stage\workspace\v2\quickstart\npm-debug.log
`

**Comment by neerajraigit** [comment] 2016-09-30 09:17
node -v : 6.7.0
npm -v : 3.10.3

```
>npm start

> angular-quickstart@1.0.0 start C:\Users\BMRC_Special\My Documents\angular-quickstart
> tsc && concurrently "tsc -w" "lite-server"

[0] 2:29:57 PM - Compilation complete. Watching for file changes.
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync config **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   watchOptions: { ignored: 'node_modules' },
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: watch index.html EPERM
[1]     at exports._errnoException (util.js:1036:11)
[1]     at FSWatcher.start (fs.js:1429:19)
[1]     at Object.fs.watch (fs.js:1456:11)
[1]     at createFsWatchInstance (C:\Users\BMRC_Special\Documents\angular-quickstart\node_modules\chokidar\lib\nodefs-handler.js:37:15)
[1]     at setFsWatchListener (C:\Users\BMRC_Special\Documents\angular-quickstart\node_modules\chokidar\lib\nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\Users\BMRC_Special\Documents\angular-quickstart\node_modules\chokidar\lib\nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleFile (C:\Users\BMRC_Special\Documents\angular-quickstart\node_modules\chokidar\lib\nodefs-handler.js:255:21)
[1]     at FSWatcher.<anonymous> (C:\Users\BMRC_Special\Documents\angular-quickstart\node_modules\chokidar\lib\nodefs-handler.js:473:21)
[1]     at FSReqWrap.oncomplete (fs.js:123:15)
[1] lite-server exited with code 1
[0] tsc -w exited with code null
```

**Comment by wardbell** [comment] 2016-10-03 20:28
@ivaro18  Not sure if this is the cause but you're versions of node and npm are not supported.
@raineeraj Do you get this immediately after cloning and doing an `npm install`?  It should work with your versions of node and npm.

**Comment by wardbell** [comment] 2016-10-21 04:39
Old. Closing. Please resubmit after updating your node version if the problem persists.

**Closed by wardbell** 2016-10-21 04:39 UTC
