### ISSUE TITLE
error

### ISSUE THREAD

**Issue by IreliaLi** [angular/quickstart#328] opened 2016-12-20 13:11 UTC
Administrator@▒▒▒▒-PC MINGW64 ~/Desktop/vue-2.1.4/quickstart (master)
$ npm start

> angular-quickstart@1.0.0 start C:\Users\Administrator\Desktop\vue-2.1.4\quickstart
> tsc && concurrently "tsc -w" "lite-server"

node_modules/.4.0.13@protractor/built/browser.d.ts(260,37): error TS2503: Cannot find namespace 'webdriver'.
node_modules/.4.0.13@protractor/built/browser.d.ts(267,55): error TS2503: Cannot find namespace 'webdriver'.
node_modules/.4.0.13@protractor/built/browser.d.ts(267,78): error TS2503: Cannot find namespace 'webdriver'.
node_modules/.4.0.13@protractor/built/browser.d.ts(358,31): error TS2503: Cannot find namespace 'webdriver'.
node_modules/.4.0.13@protractor/built/browser.d.ts(369,26): error TS2503: Cannot find namespace 'webdriver'.
node_modules/.4.0.13@protractor/built/browser.d.ts(425,36): error TS2503: Cannot find namespace 'webdriver'.
node_modules/.4.0.13@protractor/built/ptor.d.ts(13,29): error TS2503: Cannot find namespace 'webdriver'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Desktop\vue-2.1.4\quickstart\npm-debug.log

Administrator@▒▒▒▒-PC MINGW64 ~/Desktop/vue-2.1.4/quickstart (master)

**Comment by eboukamza** [comment] 2016-12-20 13:58
same issue

**Comment by lars-erik** [comment] 2016-12-20 14:02
Seems related to this: http://stackoverflow.com/questions/41232228/running-npm-start-fails-due-to-error
I just had the same happen in a project, and explicitly using "@types/selenium-webdriver": "2.53.33" made it work.

**Comment by filipesilva** [comment] 2016-12-20 14:10
Dupe of https://github.com/angular/quickstart/issues/325

**Closed by filipesilva** 2016-12-20 14:10 UTC
