### ISSUE TITLE
Still not working on ubuntu 

### ISSUE THREAD

**Issue by dsb005** [angular/quickstart#333] opened 2016-12-21 10:06 UTC
81513 error Linux 4.8.0-30-generic
81514 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "angular-cli"
81515 error node v4.2.6
81516 error npm  v3.5.2
81517 error file sh
81518 error code ELIFECYCLE
81519 error errno ENOENT
81520 error syscall spawn
81521 error node-sass@3.13.1 install: `node scripts/install.js`
81521 error spawn ENOENT
81522 error Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.
81522 error Make sure you have the latest version of node.js and npm installed.
81522 error If you do, this is most likely a problem with the node-sass package,
81522 error not with npm itself.
81522 error Tell the author that this fails on your system:
81522 error     node scripts/install.js
81522 error You can get information on how to open an issue for this project with:
81522 error     npm bugs node-sass
81522 error Or if that isn't available, you can get their info via:
81522 error     npm owner ls node-sass
81522 error There is likely additional logging output above.
81523 verbose exit [ 1, true ]

**Comment by filipesilva** [comment] 2016-12-21 10:59
Dupe of https://github.com/angular/quickstart/issues/327. If you still have problems, check the reply there and provide the extra information requested.

**Closed by filipesilva** 2016-12-21 10:59 UTC

**Comment by filipesilva** [comment] 2016-12-21 11:04
Actually, now that I read this issue better, you're trying to install Angular-CLI instead of the quickstart. Make an issue on https://github.com/angular/angular-cli instead.
