### ISSUE TITLE
es6 and lite-server errors

### ISSUE THREAD

**Issue by kazemihabib** [angular/quickstart#35] opened 2016-03-19 14:36 UTC
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync options **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[1] [BS] Access URLs:
[1]  ------------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://192.168.1.3:3000
[1]  ------------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://192.168.1.3:3001
[1]  ------------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] 16.03.19 17:59:33 200 GET /index.html
[1] 16.03.19 17:59:33 404 GET /styles.css
[1] 16.03.19 17:59:33 304 GET /node_modules/es6-shim/es6-shim.min.js
[1] 16.03.19 17:59:33 304 GET /node_modules/systemjs/dist/system-polyfills.js
[1] 16.03.19 17:59:33 304 GET /node_modules/angular2/bundles/angular2-polyfills.js
[1] 16.03.19 17:59:33 304 GET /node_modules/systemjs/dist/system.src.js
[1] 16.03.19 17:59:33 304 GET /node_modules/angular2/es6/dev/src/testing/shims_for_IE.js
[1] 16.03.19 17:59:33 304 GET /node_modules/rxjs/bundles/Rx.js
[1] 16.03.19 17:59:33 304 GET /node_modules/angular2/bundles/angular2.dev.js
[0] node_modules/angular2/typings/browser.d.ts(6,14): error TS2300: Duplicate identifier 'PromiseConstructor'.
[0] node_modules/angular2/typings/es6-collections/es6-collections.d.ts(22,5): error TS2300: Duplicate identifier 'done'.
[0] node_modules/angular2/typings/es6-collections/es6-collections.d.ts(23,5): error TS2300: Duplicate identifier 'value'.
[0] node_modules/angular2/typings/es6-collections/es6-collections.d.ts(46,5): error TS2300: Duplicate identifier 'size'.
[0] node_modules/angular2/typings/es6-collections/es6-collections.d.ts(52,5): error TS2300: Duplicate identifier 'prototype'.
[0] node_modules/angular2/typings/es6-collections/es6-collections.d.ts(66,5): error TS2300: Duplicate identifier 'size'.
[0] node_modules/angular2/typings/es6-collections/es6-collections.d.ts(72,5): error TS2300: Duplicate identifier 'prototype'.
[0] node_modules/angular2/typings/es6-collections/es6-collections.d.ts(88,5): error TS2300: Duplicate identifier 'prototype'.
[0] node_modules/angular2/typings/es6-collections/es6-collections.d.ts(103,5): error TS2300: Duplicate identifier 'prototype'.
[0] node_modules/angular2/typings/es6-promise/es6-promise.d.ts(11,15): error TS2300: Duplicate identifier 'Promise'.
[0] node_modules/angular2/typings/es6-promise/es6-promise.d.ts(42,16): error TS2300: Duplicate identifier 'Promise'.
[0] typings/browser/ambient/es6-shim/index.d.ts(11,5): error TS2300: Duplicate identifier 'done'.
[0] typings/browser/ambient/es6-shim/index.d.ts(12,5): error TS2300: Duplicate identifier 'value'.
[0] typings/browser/ambient/es6-shim/index.d.ts(477,11): error TS2300: Duplicate identifier 'Promise'.
[0] typings/browser/ambient/es6-shim/index.d.ts(496,11): error TS2300: Duplicate identifier 'PromiseConstructor'.
[0] typings/browser/ambient/es6-shim/index.d.ts(554,13): error TS2300: Duplicate identifier 'Promise'.
[0] typings/browser/ambient/es6-shim/index.d.ts(563,5): error TS2300: Duplicate identifier 'size'.
[0] typings/browser/ambient/es6-shim/index.d.ts(572,5): error TS2300: Duplicate identifier 'prototype'.
[0] typings/browser/ambient/es6-shim/index.d.ts(583,5): error TS2300: Duplicate identifier 'size'.
[0] typings/browser/ambient/es6-shim/index.d.ts(592,5): error TS2300: Duplicate identifier 'prototype'.
[0] typings/browser/ambient/es6-shim/index.d.ts(607,5): error TS2300: Duplicate identifier 'prototype'.
[0] typings/browser/ambient/es6-shim/index.d.ts(621,5): error TS2300: Duplicate identifier 'prototype'.
[0] 5:59:33 PM - Compilation complete. Watching for file changes.
[1] [BS] File changed: app/app.component.js
[1] [BS] File changed: app/main.js
[1] [BS] File changed: app/sayHello.js
[1] 16.03.19 17:59:33 200 GET /app/main.js
[1] 16.03.19 17:59:33 200 GET /app/app.component.js
[1] events.js:154
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: watch node_modules/browser-sync/node_modules/lodash/lang/isNumber.js ENOSPC
[1]     at exports._errnoException (util.js:890:11)
[1]     at FSWatcher.start (fs.js:1313:19)
[1]     at Object.fs.watch (fs.js:1341:11)
[1]     at createFsWatchInstance (/run/media/habib/New Volume/projects/angular2/learn-from-doc/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/run/media/habib/New Volume/projects/angular2/learn-from-doc/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/run/media/habib/New Volume/projects/angular2/learn-from-doc/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleFile (/run/media/habib/New Volume/projects/angular2/learn-from-doc/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[1]     at FSWatcher.<anonymous> (/run/media/habib/New Volume/projects/angular2/learn-from-doc/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[1]     at FSReqWrap.oncomplete (fs.js:82:15)
[1] 
[1] npm
[1]  
[1] ERR! Linux 4.4.5-1-MANJARO
[1] npm ERR! 
[1] argv "/usr/bin/node" "/usr/bin/npm" "run" "lite"
[1] npm ERR! node v5.8.0
[1] npm 
[1] ERR! npm  v3.8.2
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! angular2-quickstart@1.0.0 lite: `lite-server`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the angular2-quickstart@1.0.0 lite script 'lite-server'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm
[1]  ERR! If you do, this is most likely a problem with the angular2-quickstart package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     lite-server
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs angular2-quickstart
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls angular2-quickstart
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm 
[1] ERR! Please include the following file with any support request:
[1] npm ERR!     /run/media/habib/New Volume/projects/angular2/learn-from-doc/npm-debug.log
[1] npm run lite exited with code 1

[npm-debug.log.tar.gz](https://github.com/angular/quickstart/files/180854/npm-debug.log.tar.gz)

**Comment by wardbell** [comment] 2016-03-19 23:44
I'm sorry but I cannot duplicate. 

Works fine for me. What is your environment? What node version? What did you clone? 

Are you updating or starting from scratch? If updating, is it possible that you have multiple shim versions for the same shim library in your typings folder? If so, the easiest thing is to discard the repo and clone again.

### My Console Log
On Windows, node v.5.6, npm v.3.6.0 ... after the following ...

* clone the repo for beta.11, (commit 0fb8db4de578b41300dfde84f7fbb06a3f563b11)
* `npm install`
* `npm start`

... I see this (and the app displays in the browser) ...
```
> npm start

> angular2-quickstart@1.0.0 start C:\github\_angular-quickstart
> concurrently "npm run tsc:w" "npm run lite"

[1]
[1] > angular2-quickstart@1.0.0 lite C:\github\_angular-quickstart
[1] > lite-server
[1]
[0]
[0] > angular2-quickstart@1.0.0 tsc:w C:\github\_angular-quickstart
[0] > tsc -w
[0]
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync options **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[0] 4:30:33 PM - Compilation complete. Watching for file changes.
[1] [BS] Access URLs:
[1]  -------------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://192.168.1.80:3000
[1]  -------------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://192.168.1.80:3001
[1]  -------------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] 16.03.19 16:30:35 200 GET /index.html
[1] 16.03.19 16:30:36 200 GET /styles.css
[1] 16.03.19 16:30:36 200 GET /node_modules/es6-shim/es6-shim.min.js
[1] 16.03.19 16:30:36 200 GET /node_modules/angular2/es6/dev/src/testing/shims_for_IE.js
[1] 16.03.19 16:30:36 200 GET /node_modules/systemjs/dist/system-polyfills.js
[1] 16.03.19 16:30:36 200 GET /node_modules/angular2/bundles/angular2-polyfills.js
[1] 16.03.19 16:30:37 200 GET /node_modules/systemjs/dist/system.src.js
[1] 16.03.19 16:30:37 200 GET /node_modules/rxjs/bundles/Rx.js
[1] 16.03.19 16:30:38 200 GET /node_modules/angular2/bundles/angular2.dev.js
[1] 16.03.19 16:30:39 200 GET /app/main.js
[1] 16.03.19 16:30:39 200 GET /app/app.component.js
```

**Comment by Foxandxss** [comment] 2016-03-19 23:48
I cannot duplicate it either. Node 5.5.0, npm 3.7.2 and OSX.

**Comment by kazemihabib** [comment] 2016-03-20 09:27
I tried cloning https://github.com/angular/quickstart and I tried do it with copy the files in  https://angular.io/docs/ts/latest/tutorial/ and do npm install   in both windows and linux.
I also updated the npm and node to latest version.
It can detect the changes and transpile TypeScript to JavaScript but it can not refresh browser and sometimes server terminates with exit code 1

**Comment by jc275** [comment] 2016-03-21 10:37
Using xubuntu 14.04, node 4.4.0, npm 2.14.20.

The following opens index.html in a new browser tab, but fails to live-update it and even locks the app's files against editing.

```
$ npm start

> angular2-quickstart@1.0.0 start /home/jonathan/workspace/angular2-quickstart
> concurrently "npm run tsc:w" "npm run lite" 

[1] 
[1] > angular2-quickstart@1.0.0 lite /home/jonathan/workspace/angular2-quickstart
[1] > lite-server
[1] 
[0] 
[0] > angular2-quickstart@1.0.0 tsc:w /home/jonathan/workspace/angular2-quickstart
[0] > tsc -w
[0] 
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync options **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[1] [BS] Access URLs:
[1]  ------------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://192.168.1.2:3000
[1]  ------------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://192.168.1.2:3001
[1]  ------------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] 16.03.21 10:14:30 304 GET /index.html
[0] 10:14:33 AM - Compilation complete. Watching for file changes.
[1] 16.03.21 10:14:34 304 GET /styles.css
[1] 16.03.21 10:14:34 304 GET /node_modules/es6-shim/es6-shim.min.js
[1] 16.03.21 10:14:34 304 GET /node_modules/systemjs/dist/system-polyfills.js
[1] 16.03.21 10:14:34 304 GET /node_modules/angular2/es6/dev/src/testing/shims_for_IE.js
[1] 16.03.21 10:14:34 304 GET /node_modules/angular2/bundles/angular2-polyfills.js
[1] 16.03.21 10:14:34 304 GET /node_modules/systemjs/dist/system.src.js
[1] [BS] File changed: app/app.component.js
[1] [BS] File changed: app/main.js
[1] 16.03.21 10:14:34 304 GET /node_modules/rxjs/bundles/Rx.js
[1] 16.03.21 10:14:34 304 GET /node_modules/angular2/bundles/angular2.dev.js
[1] 16.03.21 10:14:36 200 GET /app/main.js
[1] 16.03.21 10:14:37 200 GET /app/app.component.js
[1] events.js:141
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: watch node_modules/typings/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/node_modules/readable-stream/lib/_stream_passthrough.js ENOSPC
[1]     at exports._errnoException (util.js:870:11)
[1]     at FSWatcher.start (fs.js:1234:19)
[1]     at Object.fs.watch (fs.js:1262:11)
[1]     at createFsWatchInstance (/home/jonathan/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/home/jonathan/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/jonathan/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleFile (/home/jonathan/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[1]     at FSWatcher.<anonymous> (/home/jonathan/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[1]     at FSReqWrap.oncomplete (fs.js:82:15)
[1] 
[1] npm
[1]  
[1] ERR!
[1]  Linux 3.19.0-51-generic
[1] npm
[1]  
[1] ERR!
[1]  
[1] argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lite"
[1] npm ERR! node v4.4.0
[1] npm ERR! 
[1] npm  v2.14.20
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! angular2-quickstart@1.0.0 lite: `lite-server`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the angular2-quickstart@1.0.0 lite script 'lite-server'.
[1] npm ERR! This is most likely a problem with the angular2-quickstart package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     lite-server
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs angular2-quickstart
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR! 
[1] npm ERR!     npm owner ls angular2-quickstart
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm
[1]  
[1] ERR!
[1]  Please include the following file with any support request:
[1] npm ERR!     /home/jonathan/workspace/angular2-quickstart/npm-debug.log
[1] npm run lite exited with code 1
```

**Comment by jc275** [comment] 2016-03-21 12:14
Related: https://github.com/johnpapa/lite-server/issues/54

**Comment by rassiesmit** [comment] 2016-03-24 19:54
Had the same problem on Fedora 23, using various node and npm versions.   I found this solution that worked for me:
Related: angular/angular#6097
Another reference that contains some interesting links in the comments:
http://stackoverflow.com/questions/34399445/angular-2-quickstart-live-server-error

**Comment by Foxandxss** [comment] 2016-03-24 23:40
We updated the quickstart to all the latest versions.

Could we confirm if this is still a problem?

Thank you.

**Comment by bengy** [comment] 2016-03-25 00:13
I also had the same issue (fs.inotify.max_user_watches was too low) but it works now. I think the problem is that lite-server watches all files, including node_modules, which totals in about 10600 files. This may be fixed by [this](https://github.com/johnpapa/lite-server/pull/57) pull request.

**Comment by wardbell** [comment] 2016-03-25 01:38
Closing as this is not a QS issue

**Closed by wardbell** 2016-03-25 01:38 UTC
