### ISSUE TITLE
Not Running on Ubuntu ...

### ISSUE THREAD

**Issue by dsb005** [angular/quickstart#327] opened 2016-12-20 10:45 UTC
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

Error Messege:
npm ERR! Linux 4.8.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saleh/workspace/js/angular/quickstart/npm-debug.log

**Comment by filipesilva** [comment] 2016-12-20 17:08
Heya, was there any other message on the console when you ran mom start?

These npm error logs aren't showing the real error.

**Comment by jsanchesleao** [comment] 2016-12-20 17:10
having the same problem here. This is the output I receive:

```
$ npm start

> angular-quickstart@1.0.0 start /home/ideais/estudos/ng2/pokedex/pokedex
> tsc && concurrently "tsc -w" "lite-server" 

node_modules/protractor/built/browser.d.ts(260,37): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(267,55): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(267,78): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(358,31): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(369,26): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(425,36): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/ptor.d.ts(13,29): error TS2503: Cannot find namespace 'webdriver'.

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/home/ideais/.nvm/versions/v6.2.1/bin/node" "/home/ideais/.nvm/versions/v6.2.1/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ideais/estudos/ng2/pokedex/pokedex/npm-debug.log
```

**Comment by filipesilva** [comment] 2016-12-20 17:48
Then this sounds like a dupe of https://github.com/angular/quickstart/issues/325, see https://github.com/angular/quickstart/issues/325#issuecomment-268118533 for a solution.

**Closed by filipesilva** 2016-12-20 17:48 UTC
