### ISSUE TITLE
imports in tests looking in wrong place for imported modules (/base/app/... instead of /app/...)

### ISSUE THREAD

**Issue by TheManSpeaker** [angular/quickstart#240] opened 2016-10-06 17:56 UTC
I have a test in /app/Lib/SmartDateFormatPipe.spec.ts:

```
import { SmartDateFormatPipe } from "./SmartDateFormatPipe";

describe("SmartDateFormatPipe", () => {
    let pipe: SmartDateFormatPipe = new SmartDateFormatPipe();

    it('transforms (null, "YYYY-MM-DD") to empty string', () => expect(pipe.transform(null, "YYYY-MM-DD")).toBe(""));
    it('transforms ("01/01/2000", "YYYY-MM-DD") to empty string', () => expect(pipe.transform("01/01/2000", "YYYY-MM-DD")).toBe("2000-01-01"));
});
```

Which is importing this module in the same directory:

```
import {Pipe, PipeTransform} from "@angular/core";
import * as moment from "moment";

@Pipe({ name: "smartDateFormat" })
export class SmartDateFormatPipe implements PipeTransform {
    transform(value: string, format: string): string {
        let parsedDate: number = Date.parse(value);
        let result: string = "";

        if (isNaN(parsedDate)) {
            return result;
        }

        if (/\d+\/\d+\/\d{4}/.test(value)) {
            result = moment(value, 'M/D/YYYY').format(format);
        } else if (/\d{4}-\d{2}-\d{2}/.test(value)) {
            result = moment(value, 'YYYY-MM-DD').format(format);
        } else {
            result = moment(parsedDate).format(format);
        }

        return result;
    }
}
```

When I start karma, I'm seeing this error after it loads up the browser:

```
[1] 06 10 2016 13:52:46.663:WARN [web-server]: 404: /base/app/Lib/SmartDateFormatPipe
[1] Chrome 53.0.2785 (Windows 10 0.0.0) ERROR
[1]   {
[1]     "originalErr": {}
[1]   }
[1]
[1] Chrome 53.0.2785 (Windows 10 0.0.0) ERROR
[1]   {
[1]     "originalErr": {}
[1]   }
```

My karma.conf.js & karma-test-shim.js are copied directly from this repository.

Anyone know what's up?

**Comment by wardbell** [comment] 2016-10-10 06:14
Duplicate of #241

**Closed by wardbell** 2016-10-10 06:14 UTC
Labels: duplicate

**Comment by naresh-n** [comment] 2016-12-05 20:44
The issue is you need to provide right directory structure to load all files by karma
if you look at angular-quickstart repo -> karma.config.js. A simple missing '/' would change the file pattern load.

var appBase = 'dist/src/';
{ pattern: appBase + '**/*.js', included: false, watched: true },
