### ISSUE TITLE
Error on "npm install" ERR! cb() never called!

### ISSUE THREAD

**Issue by maximklakov** [angular/quickstart#62] opened 2016-04-15 05:33 UTC
Hi! 
I've started to receive error message "ERR! cb() never called!" when i'm running 
`npm install`

I've tried to clean up the npm-cache, but it does not help.

I've checked out commit cd290d9558a4e4932a5c3f0521650eb2df2f9354 and it works fine for me.

**Comment by Foxandxss** [comment] 2016-04-15 11:21
I can confirm this. I will research later.

**Comment by Foxandxss** [comment] 2016-04-15 17:27
So it is a reported issue already https://github.com/angular/angular/issues/8053.

With node 5.10.1 it works like a charm.

**Comment by wardbell** [comment] 2016-04-18 02:23
Closing because no action required here

**Closed by wardbell** 2016-04-18 02:23 UTC
Labels: wontfix

**Comment by maximklakov** [comment] 2016-04-18 06:31
You must be joking! 
Current version of node is [v4.4.3](https://nodejs.org/en/download/)
where should I find version 5.10 ???

You are providing TUTORIAL for a quick start - it should be as easy as 
download this, 
download that, 
install and work!

**Comment by filipesilva** [comment] 2016-04-18 13:18
@maximklakov you can add your input in the main issue that @Foxandxss pointed out: https://github.com/angular/angular/issues/8053

That is the issue that tracks the node/angular problem, not this one. Issues with npm and angular itself aren't something that can be solved in this repo, because this is the quickstart.
