### ISSUE TITLE
Why it is not for production?

### ISSUE THREAD

**Issue by Valonix** [angular/quickstart#298] opened 2016-11-22 23:13 UTC
I just started to learn Angular 2 with TS, i know Angular 1.5x very well. I have one question. 

> This is not the perfect arrangement for your application. It is not designed for production. It exists primarily to get you started quickly with learning and prototyping in Angular

Why? What exactly not for production?
Thanks...

**Comment by ranjithprabhuk** [comment] 2016-11-28 11:53
Production and build process need to defined. Its very important to bundle and minify the js files for production.

**Comment by Valonix** [comment] 2016-11-28 11:56
I can do this in this quick start?

**Comment by wardbell** [comment] 2016-11-30 20:20
You can build an app on this seed and then add production build capabilities later. That is by design. Maybe we'll change our mind about that later but I'm closing this issue because we do not intend to take those steps at the moment.

We will be adding documentation on readying your app for production in the not distant future.

**Closed by wardbell** 2016-11-30 20:20 UTC

**Comment by Valonix** [comment] 2016-11-30 21:00
OK, thanks. Will be cool if it be in docs. Because right now all docs about local development....

**Comment by wardbell** [comment] 2016-11-30 22:53
We agree. It's in our plans to talk about this. Just haven't gotten there yet.
